apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-client-provisioner-logging
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner-logging
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner-logging
    spec:
      serviceAccountName: nfs-client-provisioner-logging
      containers:
        - name: nfs-client-provisioner-logging
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/logging
            - name: NFS_SERVER
              value: fsf-seo0101a-fz.adn.networklayer.com
            - name: NFS_PATH
              value: /IBM02SV1365537_11/data01
      volumes:
        - name: nfs-client-root
          nfs:
            server: fsf-seo0101a-fz.adn.networklayer.com
            path: /IBM02SV1365537_11/data01
